apiVersion: v1
kind: Service
metadata:
  name: env-healing-agent
  namespace: env-healing-agent-ns
  labels:
    app: env-healing-agent
spec:
  type: ClusterIP
  selector:
    app: env-healing-agent
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
